### ISSUE TITLE
您好，请问Mac这个要怎么使用，还请明示，我安装完脚本配置后报错

### ISSUE THREAD

**Issue by AnriKaede** [davidkingzyb/pccold#10]
pccoldvideo
Traceback (most recent call last):
  File "/usr/local/bin/pccoldvideo", line 4, in <module>
    __import__('pkg_resources').run_script('pccold==0.17', 'pccoldvideo')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/pccoldvideo' not found in metadata at '/usr/local/lib/python3.7/site-packages/pccold-0.17.dist-info'

**Comment by AnriKaede** [comment]
python3 pccold.py
Traceback (most recent call last):
  File "pccold.py", line 27, in <module>
    from .tools import sendEmails,saveStream,testRoomStatus,pidpool,ReturnCodeObserverThread,SleepKillerThread
ModuleNotFoundError: No module named '__main__.tools'; '__main__' is not a package
[1]+  Exit 1                  nohup python3 pccold.py

**Comment by davidkingzyb** [comment]
不好意思，没能在mac复现你的问题，尝试直接`$ pccold`或 `$ pccoldvideo`?

**Comment by AnriKaede** [comment]
谢谢，是 python3 安装的命令路径问题

**Comment by davidkingzyb** [comment]
是通过修改shebang解决的吗？
