### ISSUE TITLE
跑不起来 我是小白...

### ISSUE THREAD

**Issue by cyo57** [davidkingzyb/pccold#11]
Traceback (most recent call last):
  File "/usr/local/bin/pccolddanmu", line 4, in <module>
    __import__('pkg_resources').run_script('pccold==0.17', 'pccolddanmu')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/pccold-0.17-py3.6.egg/EGG-INFO/scripts/pccolddanmu", line 2, in <module>
    # EASY-INSTALL-SCRIPT: 'pccold==0.17','pccolddanmu'
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/pccold-0.17-py3.6.egg/pccold/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/pccold-0.17-py3.6.egg/pccold/pccold.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/pccold-0.17-py3.6.egg/pccold/tools.py", line 20, in <module>
  File "/usr/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dkz/pccold.log'

**Comment by davidkingzyb** [comment]
应该是配置文件里面日志路径的原因

**Comment by cyo57** [comment]
那这个要怎么解决呢？

**Comment by davidkingzyb** [comment]
将配置文件里的log_path改成自己的
